In [ ]:
#Nama   :Juan Anemao Sokhi Zidomi
#NIM    :1103204007
#Kelas  :TK-44-G6

Melakukan import torch dan menampilkan versi torch

In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

Melakukan inisiasi nilai scalar dengan nilai 7

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

Melakukan pengecekan dimensi dengan source code "ndim"

In [ ]:
scalar.ndim

0

Menampilkan item pada variabel skalar

In [ ]:
scalar.item()

7

Melakukan inisiasi variabel vector

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Menampilkan dimensi dari vector bernilai 1

In [ ]:
vector.ndim

1

Melakukan pemeriksaan bentuk dari variabel vector

In [ ]:
vector.shape

torch.Size([2])

Melakukan inisiasi variabel MATRIX dengan 2 dimensi dan bernilai 2 arraynya

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Menampikan bentuk dimensi 2 karna memiliki 2 matriks

In [ ]:
MATRIX.ndim

2

Menampilkan bentuk dari variabel MATRIX

In [ ]:
MATRIX.shape

torch.Size([2, 2])

Melakukan pembuatan array 3 dimensi dengan 3 baris dan 3 kolom

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Menampilkan dimensi dari vector

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Menampilkan bentuk data dari variabel TENSOR

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Melakukan pembuatan variabel secara random dengan  3 baris dan 4 kolom

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9948, 0.8958, 0.9630, 0.6933],
         [0.7007, 0.2730, 0.3268, 0.0031],
         [0.6925, 0.2981, 0.0473, 0.7567]]),
 torch.float32)

Melakukan pengubahan size gambar dengan weight dan height masing-masing 224 dan menggunakan rgb

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Melakukan pengisian nilai dengan bentuk 3 baris dan 4 kolom yang bernilai 0 dan menampilkan type data

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Melakukan pengisian nilai ke variabel one dengan bentuk 3 baris dan 4 kolom yang bernilai 1 serta menampilkan tipe data

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Melakukan pengisian nilai 0 sampai dengan 10 dengan set up start=0 dan end =10

In [ ]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-19-768e03b8de80>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Melakukan pengisian nilai nilai menginput array 0 sd 10 bernilai 0

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Melakukan pembuatan tensor 1 D dengan bertipe data float kemudian menampilkan jumlah array yang telah dibuat

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Melakukan inisiasi variabel dengan tipe data float kemudian menampilkan tipe data tersebut

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Melakukan pembuatan tensor dengan 3 baris dan 4 kolom secara acak ,kemudian menampilkan bentuk,tipe data, dan device yang dipakai pada variabel some_tensor

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7840, 0.7057, 0.0304, 0.2896],
        [0.1841, 0.3093, 0.9377, 0.8328],
        [0.5202, 0.9612, 0.3877, 0.2697]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Melakukan penambahan 10 pada setiap nilai array

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Melakukan perkalian setiap nilai array

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Melakukan pengurangan sebanyak 1o pada setiap nilai array

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

Melakukan inisiasi nilai tensor

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Melakukan perkalian pada setiap nilai array dengan jumlah 10

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

Melakukan inisiasi nilai tensor

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

Melakukan perkalian pada nilai tensor dengan nilai tensor

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Menampilkan bentuk data  dari tensor

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Melakukan perkalian antar nilai array tensor

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

Melakukan perkalian matrix

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

Melakukab perkalian matrix antar nilai tensor

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Menampilkan hasil perkalian matrix dan menampilkan wall time

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.26 ms, sys: 41 µs, total: 1.3 ms
Wall time: 2.17 ms


tensor(14)

Menampilkan CPU time ,Wall time dan hasil perkalian matrix

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 1.13 ms


tensor(14)

Melakukan inisiasi variabel tensor dengan bentuk 3 x 2 kemudian menampilkan ,tetapi error karena tidak bisa melakukan perkalian matrix

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Menampilkan nilai tensor A dan Tensor b

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


Menampilkan nilai tensor A dan melakukan transpose pada tensor B dan menampilkannya

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


Menampilkan tensor A dan Tensor b bentuk data secara original dan setelah di ubah dan melakukan perkalian matrix kemudian menampilkan hasilnya

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Shortcut perkalian matrix kenapa bisa karna perkalian sesama matrix 3 x2 tidak boleh dan salah satu variabel dilakukannya transpose

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Melakukan pembuatan arsitektur model kemudian  menampilkan bentuk data

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Melakukan inisiasi nilai dengan rentang 10 dengan nilai start 0 dengan jumlah 10 dengan fungsi arrange

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Menampilkan nilai minimum dari array x yaitu 0
Menampilkan nilai maximum dari array x yaitu 90
Menghitung nilai mean dan menampilkannya dari array x
menghitung jumlah dari array x

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Menampilkan source code shortcut untuk menampilkan min,max,mean dan sum

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Melakukan inisiasi nilai dengan rentang 10 dengan nilai start 0 dengan jumlah 10 dengan fungsi arrange dan menentukan nilai min dan max berdasarkan indeks pada array tensor

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Menampilkan tipe data dari tensor yaitu float

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Melakukan pembuatan tensor dengan nilai float kemudian menampilkannya

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Melakukan inisiasi nilai dengan tipe data integer

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([2, 2, 2, 2, 2, 2, 2], dtype=torch.int8)

Melakukan arrange data dan kemudian menampilkan nilai x ddan bentuk datanya

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Melakukan reshape pada variabel x

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Memasukkan nilai array x ke nilai z

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Mengubah variabel x menjadi z

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Menggabungkan nilai variabel x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Menampilkan bentuk dan dimensi  data sebelum ,dan sesudah dilakukan proses reshape pada variabel x

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Melakukan inisiasi size awal yaitu 224,224,3 kemudian melakukan permutasi dengan mengubah letak axis kemudian menampilkannya

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Melakukan inisiasi nilai x dengan menggunakan arrange kemudian melakukan rshape dalam bentuk 1,3,3

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Menampikan nilai array secara berurutan

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Menampilkan nilai x pada indeks 1 berdasarkan baris

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

Menampilkan nilai berdasarkan kolom

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

Menampilkan nilai baris 1 dan kolom 1

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

Menampilkan nilai x

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Membuat nilai array dengan batas 1 dan batas akhir 8 secara berurutan

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Menambahkan nilai 1 pada setiap array

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([2., 2., 2., 2., 2., 2., 2.]))

Melakukan inisasi nilai dengan jumlah 7 masing-masing bernilai 1 setiap indeks

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Melakukan proses penambahan nilai 1 pada setiap indeks pada array

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Melakukan pembuatan nilai array secara random pada array a dan b dengan bentuk 3 x4

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Melakukan pembuatan array secara random dengan bentuk 3 x 4 dan menampilkannya

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])